name: Login Docker

on:
  push:
    branches: [ main ]

jobs:

  login-docker:
    runs-on: ubuntu-latest
    environment: dockerhub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
